FROM node:20-alpine

WORKDIR /app

# Copiar archivos de dependencias del servidor para aprovechar cache
COPY src/server/package.json ./
RUN npm install --quiet

# Copiar solo los archivos necesarios para el servidor
COPY src/server ./src/server

# Definir variables de entorno
ENV NODE_ENV=production

# Exponer puerto del backend
EXPOSE 3001

# Comando para iniciar el servidor
CMD ["node", "src/server/index.js"]
