version: '3.8'

services:
  # Servicio Frontend - Aplicación React con Vite
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: juicio-monitorio-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    networks:
      - emb-network
      - app-network

  # Servicio Backend - API con Express
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: juicio-monitorio-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-465}
      - SMTP_SECURE=${SMTP_SECURE:-true}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
    restart: always
    networks:
      - emb-network
      - app-network


networks:
  app-network:
    driver: bridge
  emb-network:
    external: true
